# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sergio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisparql-layer2triple/Layer2Triple_dialog_base_.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Layer2TripleDialogBase(object):
    def setupUi(self, Layer2TripleDialogBase):
        Layer2TripleDialogBase.setObjectName("Layer2TripleDialogBase")
        Layer2TripleDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(Layer2TripleDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(Layer2TripleDialogBase)
        self.button_box.accepted.connect(Layer2TripleDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(Layer2TripleDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Layer2TripleDialogBase)

    def retranslateUi(self, Layer2TripleDialogBase):
        _translate = QtCore.QCoreApplication.translate
        Layer2TripleDialogBase.setWindowTitle(_translate("Layer2TripleDialogBase", "QGISSPARQL-Layer2Triple"))
